package objetoshibernate;
// Generated Mar 15, 2016 4:24:46 PM by Hibernate Tools 4.3.1



/**
 * Servidor generated by hbm2java
 */
public class Servidor  implements java.io.Serializable {


     private int nidusuario;
     private Usuario usuario;
     private Integer visitas;

    public Servidor() {
    }

	
    public Servidor(Usuario usuario) {
        this.usuario = usuario;
    }
    public Servidor(Usuario usuario, Integer visitas) {
       this.usuario = usuario;
       this.visitas = visitas;
    }
   
    public int getNidusuario() {
        return this.nidusuario;
    }
    
    public void setNidusuario(int nidusuario) {
        this.nidusuario = nidusuario;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Integer getVisitas() {
        return this.visitas;
    }
    
    public void setVisitas(Integer visitas) {
        this.visitas = visitas;
    }




}


